package com.smartlearning.platform.service.impl;

import com.smartlearning.platform.config.AppProperties;
import com.smartlearning.platform.dto.course.LessonRequest;
import com.smartlearning.platform.dto.course.ModuleRequest;
import com.smartlearning.platform.dto.upload.AutoGeneratedModulesResponse;
import com.smartlearning.platform.entity.Course;
import com.smartlearning.platform.entity.User;
import com.smartlearning.platform.exception.BadRequestException;
import com.smartlearning.platform.exception.UnauthorizedException;
import com.smartlearning.platform.service.StorageService;
import com.smartlearning.platform.service.UploadService;
import lombok.RequiredArgsConstructor;
import org.apache.tika.Tika;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.*;
import java.util.Locale;

@Service
@RequiredArgsConstructor
public class UploadServiceImpl implements UploadService {

    private final SupportService supportService;
    private final StorageService storageService;
    private final AppProperties appProperties;
    private final Tika tika = new Tika();

    @Override
    @Transactional
    public AutoGeneratedModulesResponse uploadVideos(Long courseId, MultipartFile[] videos, String userEmail) {
        User user = supportService.getUserByEmail(userEmail);
        Course course = supportService.getCourse(courseId);
        if (!course.getCreator().getId().equals(user.getId())) {
            throw new UnauthorizedException("Only the course creator can upload videos");
        }

        Map<String, List<LessonRequest>> grouped = new LinkedHashMap<>();
        for (MultipartFile video : videos) {
            validateVideo(video);
            String storedPath = storageService.store(video, "videos/" + courseId);
            String fileName = Objects.requireNonNullElse(video.getOriginalFilename(), "lesson.mp4");
            String suggestedModule = suggestModule(fileName);
            List<LessonRequest> lessons = grouped.computeIfAbsent(suggestedModule, ignored -> new ArrayList<>());
            lessons.add(new LessonRequest(null, humanizeTitle(fileName), lessons.size(), storedPath, "video/mp4", video.getSize(), 0));
        }

        List<ModuleRequest> modules = new ArrayList<>();
        int moduleOrder = 0;
        for (Map.Entry<String, List<LessonRequest>> entry : grouped.entrySet()) {
            modules.add(new ModuleRequest(null, entry.getKey(), moduleOrder++, entry.getValue()));
        }
        return new AutoGeneratedModulesResponse(modules);
    }

    private void validateVideo(MultipartFile file) {
        if (file.isEmpty()) {
            throw new BadRequestException("Empty file is not allowed");
        }
        if (file.getSize() > appProperties.getStorage().getMaxVideoSizeBytes()) {
            throw new BadRequestException("Video exceeds configured file size limit");
        }

        String fileName = Objects.requireNonNullElse(file.getOriginalFilename(), "").toLowerCase(Locale.ROOT);
        if (!fileName.endsWith(".mp4")) {
            throw new BadRequestException("Only .mp4 video files are allowed");
        }

        try {
            String detectedMimeType = tika.detect(file.getInputStream(), file.getOriginalFilename());
            String declaredMimeType = Objects.requireNonNullElse(file.getContentType(), "").toLowerCase(Locale.ROOT);

            boolean allowed = appProperties.getStorage().getAllowedVideoTypes().contains(detectedMimeType)
                    || appProperties.getStorage().getAllowedVideoTypes().contains(declaredMimeType)
                    || "application/mp4".equalsIgnoreCase(detectedMimeType)
                    || "application/mp4".equalsIgnoreCase(declaredMimeType)
                    || "application/octet-stream".equalsIgnoreCase(detectedMimeType)
                    || "application/octet-stream".equalsIgnoreCase(declaredMimeType);

            if (!allowed) {
                throw new BadRequestException(
                        "Only MP4 videos are allowed. Detected type: " + detectedMimeType
                                + (declaredMimeType.isBlank() ? "" : ", uploaded as: " + declaredMimeType)
                );
            }
        } catch (IOException ex) {
            throw new BadRequestException("Could not validate video");
        }
    }

    private String suggestModule(String fileName) {
        String normalized = fileName.toLowerCase(Locale.ROOT);
        if (normalized.contains("basic") || normalized.startsWith("01") || normalized.startsWith("1")) return "Basics";
        if (normalized.contains("intermediate") || normalized.startsWith("02") || normalized.startsWith("2")) return "Intermediate";
        if (normalized.contains("advanced") || normalized.startsWith("03") || normalized.startsWith("3")) return "Advanced";
        String[] parts = fileName.split("[-_]");
        return parts.length > 1 ? capitalize(parts[0]) : "Core Lessons";
    }

    private String humanizeTitle(String fileName) {
        return fileName.replace(".mp4", "").replace("_", " ").replace("-", " ").trim();
    }

    private String capitalize(String value) {
        return value.substring(0, 1).toUpperCase(Locale.ROOT) + value.substring(1).toLowerCase(Locale.ROOT);
    }
}
