package com.smartlearning.platform.dto.upload;

import com.smartlearning.platform.dto.course.ModuleRequest;

import java.util.List;

public record AutoGeneratedModulesResponse(List<ModuleRequest> modules) {
}
