package com.smartlearning.platform.controller;

import com.smartlearning.platform.dto.upload.AutoGeneratedModulesResponse;
import com.smartlearning.platform.service.UploadService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

@RestController
@RequestMapping("/api/upload")
@RequiredArgsConstructor
public class UploadController {

    private final UploadService uploadService;

    @PostMapping("/{courseId}/videos")
    public ResponseEntity<AutoGeneratedModulesResponse> uploadVideos(
            @PathVariable Long courseId,
            @RequestPart("videos") MultipartFile[] videos,
            Authentication authentication) {
        return ResponseEntity.ok(uploadService.uploadVideos(courseId, videos, authentication.getName()));
    }
}
