package com.smartlearning.platform.service;

import com.smartlearning.platform.dto.upload.AutoGeneratedModulesResponse;
import org.springframework.web.multipart.MultipartFile;

public interface UploadService {
    AutoGeneratedModulesResponse uploadVideos(Long courseId, MultipartFile[] videos, String userEmail);
}
